### ISSUE TITLE
[Feature Request] Add support for multiple CustomModelData textures

### ISSUE THREAD

**Issue by Notoriousi** [henkelmax/peek#14]
When working with multiple CustomModelData nbt on the same item it applies the highest number of the custom model to the texture.
For example:
The diamond is number 5 and the netherite one is number 6:
![image](https://github.com/henkelmax/peek/assets/94121814/43b98052-63d3-41df-b6e6-77db92ac4b24)
When they are in shulkers only the highest number (6) is applied no matter the applied CustomModelData: 
![image](https://github.com/henkelmax/peek/assets/94121814/c3731cf7-0d03-4152-8d7a-4b88f697498d) (First shulker has number 5 applied and second shulker has number 6)

I'm not sure if its planned or possible to even do but it would be nice to have the mod check for the right CustomModelData nbt texture and apply that one instead of only the highest number availible.

**Comment by henkelmax** [comment]
It is not possible to support custom model data, as the item displayed on the shulker box has its own custom model data for resource packs
