### ISSUE TITLE
Configuration question, item and label

### ISSUE THREAD

**Issue by tibucci** [henkelmax/peek#15]
Sorry if this is a stupid question or if i have missinterpreted how the mod works but how do i reproduce the shulkers on the first screenshot of the mod page? 
for example: i'd like for the shulker to render redstone dust and the name of the box as "redstone" but have inside all my redstone component. i've tried messing around but if i call the box "redstone" i only get the item rendered, if i call it "redstone box" i only get the name. 
do the boxes that have both a label and a item in your screenshoot all containing a single type of item? is the "ores" box only filled with gold? does the "tools" box only have picks?
i seem to remeber xisuma simply appending the name of the item to the end of the shulker name but i don't know if he has a costum version or something.
if it is possible to set it up like this, can you tell me how?

thank you for the great mod and sorry for my broken english

**Comment by henkelmax** [comment]
https://modrepo.de/minecraft/peek/wiki/shulker_box_hints
