### ISSUE TITLE
Mod Prevents Server from Fully Stopping

### ISSUE THREAD

**Issue by DavidMacDonald11** [henkelmax/peek#18]
**Bug description**
When this mod is installed on a fabric server, the server will close as per usual, but the java process itself will not end without pressing Ctrl-c in the terminal, or killing the process in some other way.

**Steps to reproduce the issue**
1. I have created a [test server](https://drive.google.com/file/d/1kpEas9ha8jPwOXVBeyaKQU3t8ZBUrqv1/view?usp=sharing) which has the issue. However, its bad practice to trust those sorts of links (may I suggest a virtual machine). So:
OR
1. Download the [latest fabric server version](https://fabricmc.net/use/server/) into some folder.
2. Run it with java -jar SERVER.jar
3. Edit the EULA file to agree.
4. Place Peek and fiber api into mods folder.
5. Run the server again, and enter the stop command into the gui window after it finishes loading.
6. Notice that the server process doesn't stop.

**Expected behavior**
I would expect the server to fully end, restoring terminal functionality and removing the server's PID from the system.

**Log files**
https://gist.github.com/DavidMacDonald11/1e4a42d16d29099edaa6060c5be1398a

**Versions**
- Minecraft version 1.20.2
- Fabric loader version 0.14.28
- Mod version 1.20.2-1.1.1

**Other mods**
Only other mod is fabric-api-0.90.7+1.20.2

**Screenshots (Optional)**
![image](https://github.com/henkelmax/peek/assets/50472671/414bb89e-7a7e-47a7-8afa-8f64d90cca3e)
![image](https://github.com/henkelmax/peek/assets/50472671/5e00fb49-211f-4ee3-a32a-d3532671eec9)

**Comment by henkelmax** [comment]
Does this also happen with the latest version of the mod?

**Comment by DavidMacDonald11** [comment]
My bad, the mod version is 1.20.2-1.1.10
![image](https://github.com/henkelmax/peek/assets/50472671/86627c75-29e3-4dd9-98d9-8e8f88f0467d)
