### ISSUE TITLE
Shulker box picking incorrect model

### ISSUE THREAD

**Issue by johndrinkwater** [henkelmax/peek#21]
**Bug description**
Shulker box of sticks is picking an overridden custommodeldata:10’s texture rather than the base model stick. No hint is set.
OK, that wasn’t explained very well, but: my indev resource pack has a custom model of stick for the armor statues datapack https://www.curseforge.com/minecraft/customization/armor-statues-datapack and it’s been fine until I noticed this behaviour in Peek.

May be doing something daft with resourcepacks but is this an interaction with the mod setting its own CMD **1702**, if so can I avoid this clash?

This is models/item/stick.json
```
{
  "parent": "minecraft:item/handheld",
  "textures": {
    "layer0": "minecraft:item/stick"
  },
  "overrides": [
    { "predicate": {"custom_model_data": 10}, "model": "item/pointer_wand"}
  ]
}
```
item/pointer_wand sets layer0 to pointer_wand.png, nothing special.

**Steps to reproduce the issue**
1. Install this (sorry, its a work in progress) resource pack [jdw-resource-pack-v0.1.zip](https://github.com/henkelmax/peek/files/14015392/jdw-resource-pack-v0.1.zip)
2. Put sticks in a shulker
3. Have `Show Shulker Box Items` enabled
4. See incorrect texture

**Expected behavior**
Shulker box shows stick as an item hint

**Versions**
- Minecraft 1.20.4
- Fabric 0.15.1
- Peek v1.20.4-1.1.12

**Other mods**
appleskin 2.5.1+mc1.20.3, betterf3 9.0.0, betterstats 3.7.1+fabric-1.20.4, bobby 5.0.3, cloth-config 13.0.114, continuity 3.0.0-beta.4+1.20.2, fabric-api 0.91.2+1.20.4, fabric-language-kotlin 1.10.16+kotlin.1.9.21, fabricloader 0.15.1, indium 1.0.28+mc1.20.4, inventoryprofilesnext 1.10.9, libipn 4.0.1, litematica 0.17.0, malilib 0.18.0, minecraft 1.20.4, minihud 0.30.0, mobhealthbar 2.3.0, modmenu 9.0.0, peek 1.20.4-1.1.12, respackopts 4.7.2, shulkerboxtooltip 4.0.5+1.20.2, sodium 0.5.5, tweakeroo 0.19.0, xaerominimap 23.9.6, xaeroworldmap 1.37.6, yet_another_config_lib_v3 3.3.1+1.20.4

**Screenshots**
Notice I am holding a stick in the hot-bar, the shulker only has sticks inside, both the held texture and hot-bar are `stick` model in both shots, only Peek is selecting that model when the pack is enabled.

Without resource pack enabled
![2024-01-22_21 17 36](https://github.com/henkelmax/peek/assets/7708/75abd520-66ca-4d01-b340-37b1ad35c16d)
With resource pack
![2024-01-22_21 17 10](https://github.com/henkelmax/peek/assets/7708/e9507a52-9774-4239-ad74-fbcec91e12b9)

**Comment by henkelmax** [comment]
This is intended. The custom model data is always overridden to 1702, in order for resource packs to set their own shulker box icon. I am open to feedback on how else to implement it.

**Comment by johndrinkwater** [comment]
Hmm. I guess I didn’t consider how Minecraft did overrides..  after playing in single player and finding any stick between 11 and 1702 have 10’s model, maybe I should redefine stick to use the original model for 11, and that’ll work around for my purposes.

I can’t see how Peek could retain the flexibility to have custom icons without defaulting to a preset value. But I am fairly new to poking packs.

**Comment by johndrinkwater** [comment]
If you used 1702 (or rather shulkerBoxItemHintCustomModelData) to increment the found item’s custommodeldata rather than just set it absolutely, resourcepacks could set custom models (so in my case, 1702 + 1712) while supporting existing resourcepacks that set something at 1702

**Comment by henkelmax** [comment]
> If you used 1702 (or rather shulkerBoxItemHintCustomModelData) to increment the found item’s custommodeldata rather than just set it absolutely, resourcepacks could set custom models (so in my case, 1702 + 1712) while supporting existing resourcepacks that set something at 1702

But that would in turn cause issues with resource packs that don't use that trick. It would also create conflicts with resource packs that have a higher ID.

**Comment by johndrinkwater** [comment]
Just trying to think of the most systemic way of supporting base models for items, and additional custom models, and letting Peek, peek them.

All existing resource packs using custom_model_data will have incorrect items visible in Peek, unless they have used numbers higher than 1702. Number conflicts will occur, I can’t argue against that, giving guidance to avoid stomping on that range might help.

Another option is using custom_model_data from displayItem if set, otherwise using the Peek value. But then you lose the ability to theme all %item% (lets say, sticks) as the packs’ custom model.

**Comment by henkelmax** [comment]
Yeah... I've also thought about adding another tag to resource pack loading, but that would need to hook very deep into Minecrafts resource loading code.

**Comment by johndrinkwater** [comment]
Adjusted the code to support that latter suggestion of mine, being able to use custom model data if set (ShulkerHintData now stores an ItemStack rather than Item), and it seems to work as intended. Side benefit it adds potion colour rendering as NBT is passed through.

Went to look for some public resource packs with peek overrides and my google fu is a bit weak today, do you have a custom one?

What’s the reasoning to avoid ItemStack, memory usage?

Correct sticks
![2024-01-23_15 15 46](https://github.com/henkelmax/peek/assets/7708/0d23145b-c978-4d56-acd4-6e4af27e6a09)
Correct potions
![2024-01-23_15 19 06](https://github.com/henkelmax/peek/assets/7708/6e70b9f7-4ac6-4c60-8b60-333705c02bb8)

**Comment by henkelmax** [comment]
> Went to look for some public resource packs with peek overrides and my google fu is a bit weak today, do you have a custom one?
No, I don't know of any resource packs that are public.

> What’s the reasoning to avoid ItemStack, memory usage?

No idea TBH :D I think because of the determining of the shown item. So that a box of swords with different enchantments shows a general swords. But you could technically also do that with stacks and ignoring NBT.

**Comment by johndrinkwater** [comment]
> > Went to look for some public resource packs with peek overrides and my google fu is a bit weak today, do you have a custom one?
> 
> No, I don't know of any resource packs that are public.

OK, made a quick resource pack out of https://github.com/ThePotatoKing55/2D-block-texture-pack with support for ~550 items, I know there’s a fork with additional blocks that I’ll look at when I can. It demos using custom models solely for Peek shulker labelling.

Hope this listing is ok with you (especially logo)
https://www.curseforge.com/minecraft/texture-packs/peek-flat-shulker-icons

> No idea TBH :D I think because of the determining of the shown item. So that a box of swords with different enchantments shows a general swords. But you could technically also do that with stacks and ignoring NBT.

After poking through the API, something can probably be rustled up that makes a mixed box of potions have a potion label still, ItemStack.isSameItemSameTags vs ItemStack.isSameItem

Got a bit hung up on odd rendering behaviours, when I stoppped looking at it last week, heads with NBT rendering like GUI (45°), heads without NBT rendering like a block. Wasn’t certain why codepath was doing that...

**Comment by henkelmax** [comment]
> Hope this listing is ok with you (especially logo)
https://www.curseforge.com/minecraft/texture-packs/peek-flat-shulker-icons

Sure, no problem

> After poking through the API, something can probably be rustled up that makes a mixed box of potions have a potion label still, ItemStack.isSameItemSameTags vs ItemStack.isSameItem

Yeah that shouldn't be an issue. I will look into that.
