### ISSUE TITLE
Objects rendered on shulkers are flipped

### ISSUE THREAD

**Issue by johndrinkwater** [henkelmax/peek#22]
### Bug description

Items on lids are 180° left-to-right flipped, compared to their rendering in item frames.

### Minecraft version

1.20.4

### Mod version

1.20.4-1.2.0

### Mod loader and version

Fabric 0.15.1

### Steps to reproduce

1. Put a diamond pick in a shulker
2. See issue

### Expected behavior

Items on shulker faces should look out of the box rather than into.

### Log files

https://gist.github.com/johndrinkwater/848f180512b23bf370484ca918029296

### Screenshots

Top row, custom model. middle row, actual item. bottom, shulkers.
![2024-02-06_16 52 30](https://github.com/henkelmax/peek/assets/7708/6b38fd12-9501-46bf-b6ea-83a0415c93c0)

Previous Peek (peek-fabric-1.20.4-1.1.12) release showed the same, it’s not a new bug.
![2024-02-06_16 14 22](https://github.com/henkelmax/peek/assets/7708/8ed129e8-286b-4017-89d3-0f85dfdb9cc1)

**Comment by henkelmax** [comment]
Thank you for reporting this issue!
