### ISSUE TITLE
Peek crashing with Optifabric

### ISSUE THREAD

**Issue by HydraheadHunter** [henkelmax/peek#23]
### Bug description

Game crashes when attempting to launch both Peek and Optifabric installed.

Each mod run fine when installed individually, but when installed together, they cause a fatal runtime exception.

### Minecraft version

1.20.4

### Mod version

1.20.4-1.3.0

### Mod loader and version

Fabric-loader-0.15.6-1.20.4

### Steps to reproduce

Attempt to run with both Peek 1.20.4-1.3.0 and preview OptiFine 1.20.4 HD U I7 pre2 (plus optifabric 1.14.3) installed.

Observe whether game crashes.  
	

### Expected behavior

Game should not crash.

### Log files

https://gist.github.com/HydraheadHunter/9dde1295d5829a2e24e560faa5459cdb

**Comment by henkelmax** [comment]
We don't provide support for OptiFine
