### ISSUE TITLE
Does not properly respect item override/predicates when selecting model to display on shulker. 

### ISSUE THREAD

**Issue by mrmindor** [henkelmax/peek#24]
### Bug description

When using a resource pack which uses overrides with predicates for selecting models. 
Peek always displays the last of the available overrides regardless of which predicate actually matches the item's state.
Peek always displays this same override even if none of the predicates match the item (Minecraft uses the default model in this case.)

A quick demonstration of this can be seen on Tango's recent stream when he places some default sticks in a shulker. 
https://youtu.be/8r2zJgy6ryU?t=647

Peek selects a padlock model Zedaph was using to display his 'locked' hot bar slots.
These freshly crafted sticks have no custom item data and should use the standard stick model rather than the custom one defined by the predicate.

I have reproduced this locally in 1.20.1 but Tango's video shows it also occurs in 1.20.4. 

### Minecraft version

1.20.1

### Mod version

1.20.1-1.1.11

### Mod loader and version

fabric-loader-0.14.25-1.20.1

### Steps to reproduce

In Minecraft launcher create an installation using the fabric loader and set custom directory.
create a mod folder within custom directory and add appropriate version of the peek jar file. 

Add the attached resources.zip resource pack to the installation. (this is the resource pack from the Hermitcraft season 9 download)

Launch minecraft
create new world (allow cheats)
give self a shulker box 
give self an iron ingot

place iron ingot in shulker box

Load resource pack.

observe Peek select the Rusty Repair Kit model from Decked Out to display on the shulker box instead of the regular iron ingot model. 

[resources.zip](https://github.com/henkelmax/peek/files/14327253/resources.zip)

### Expected behavior

The expected behavior would be that Peek selects the same model to display for the item that Minecraft itself would select. 

In the case above the expectation would be to display the standard iron nugget.

In the resource pack the file where the iron nugget's overrides are defined can be found at:
"\assets\minecraft\models\item\iron_ingot.json"
We can see the Rusty Repair Kit should only be used if the item has "custom_model_data" = 2 

### Log files

https://gist.github.com/mrmindor/11928f085d0df39961c751daa8b8b1f4

### Screenshots

![2024-02-19_00 37 30](https://github.com/henkelmax/peek/assets/10384598/acf93738-5036-46fe-87a0-43d4ca68d04c)
![2024-02-19_00 37 34](https://github.com/henkelmax/peek/assets/10384598/5f4e66b2-48b3-4706-975a-4f84e5d470e9)
![2024-02-19_00 38 05](https://github.com/henkelmax/peek/assets/10384598/fe250fe9-5702-4d50-bf6d-e3b5ab22495e)
![2024-02-19_00 38 14](https://github.com/henkelmax/peek/assets/10384598/e9aff370-1fc3-44fa-abac-3a29132f97e0)

**Comment by henkelmax** [comment]
This has already been fixed in the latest version.
