### ISSUE TITLE
Shulker Box hints disappear when containers out of render distance

### ISSUE THREAD

**Issue by ItsLeon15** [henkelmax/peek#27]
### Bug description

When you place a shulker box on the ground and open it, it will show the item above the shulker box like normal but when you leave the render distance to see that container, then go back to the shulker the icon above the shulker is gone so you have to reopen it? Is there a way to make it permanent, I don't mind having to rename it but it seems it can't remember anything which is an annoying issue.

### Minecraft version

1.20.4

### Mod version

1.20.4-1.3.1

### Mod loader and version

Fabric API 0.96.4

### Steps to reproduce

1. Place down shulker box on the ground filled with stone
2. The icon should appear above the shulker
3. Leave the container render distance
4. Return to the shulker box
5. The icon above the shulker box should not show (This is wrong).`

### Log files

N/A

**Comment by henkelmax** [comment]
This is completely normal if you don't have the mod installed on the server.
