### ISSUE TITLE
Labels not working [1.20.6]

### ISSUE THREAD

**Issue by ItsLeon15** [henkelmax/peek#29]
### Bug description

If you rename a shulker box with ``{i=oak_log;l=Spruce Log}`` it fails to show the icon and label. The resource pack is enabled!

### Minecraft version

1.20.6

### Mod version

1.20.6-1.3.1

### Mod loader and version

Fabric Loader: 0.15.11

### Steps to reproduce

1. Install Fabric 1.20.6
2. Install Peek 1.20.6-1.3.1
3. Rename a Shulker Box to ``{i=redstone;l=Redstone}``
4. Expect the Icon and Label to show, it doesn't.

### Expected behavior

The Icon and Label to appear correctly.

### Log files

N/A

### Screenshots

![2024-05-17_21 41 56](https://github.com/henkelmax/peek/assets/64979109/60950bb0-0305-4498-a581-b1e63b133e7c)
![image](https://github.com/henkelmax/peek/assets/64979109/fffeb2bd-670e-4b42-b033-1cf6d4837fc6)
![image](https://github.com/henkelmax/peek/assets/64979109/5748c64a-30a1-40bd-bec2-5fd14c5fffdd)

**Comment by ItsLeon15** [comment]
Update: Mining and replacing the shulker boxes fixes the Label and Icon not showing but the text still shows which is a bug.
![2024-05-17_21 47 05](https://github.com/henkelmax/peek/assets/64979109/362c4d0e-c1c2-4d28-a10a-ac863eabd613)

**Comment by henkelmax** [comment]
I did you exact steps to reproduce. Works perfectly fine. Make sure you have the mod installed on the server and the client.

**Comment by johndrinkwater** [comment]
@ItsLeon15 it seems you’re using https://modrinth.com/datapack/shulker-boxes-names as well as Peek, that’s why you have the floating text. The icons/labels missing may be related to #34
