### ISSUE TITLE
Create Compatibility

### ISSUE THREAD

**Issue by RavenFayrin** [henkelmax/peek#30]
### Bug description

show_shulker_box_block_hint shows shulker box hints on shulker box blocks when placed down.
This option does not work when the mod Create is loaded in too. I've ensured all the boxes are checked I've tried multiple versions of the game and the only thing I can find constantly a problem is that Create is in the mix. Chipped works with the peek so it's not added items.

show_shulker_box_item_hint shows shulker box hints on shulker box items in your inventory.
This option does work.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.3.1

### Mod loader and version

Fabric - 0.15.11

### Steps to reproduce

1. Load any single-player game (Creative to quickly reproduce problem) with Peek and Create installed on Fabric 0.15.11 version. 
2. Place a shulker down and put something in it.
3. Witness Peek not working
4. Break box and witness Peek working in the inventory.

### Expected behavior

No 3d render when a shulker with anything in it is placed down in the world.

### Log files

https://gist.github.com/RavenFayrin/1e2d1e64feaeea71796742977e2fb9a0

**Comment by henkelmax** [comment]
Sounds like an issue with create. Can you also report that to their issue tracker?

**Comment by henkelmax** [comment]
Closed due to inactivity.
