### ISSUE TITLE
Peek mod doesn't display text or items with Enhanced Block Entities mod

### ISSUE THREAD

**Issue by RottenAppleSalt** [henkelmax/peek#31]
### Bug description

When Peek is used with Enhanced Block Entities by FoundationGames, the labels and items don't appear.

### Minecraft version

1.20.4

### Mod version

fabric-1.20.4-1.3.1

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

- Install Peek (with dependencies) alongside of [Enhanced Block Entities](https://modrinth.com/mod/ebe)
- Edit the config to enable `use_shulker_box_data_strings` 
- Try to name a shulker in an anvil (example: `Rock Box {i=stone;l=Rocks}`)
---
This can be solved without uninstalling Enhanced Block Entities, but it may cause lag if lots of shulkers are present.
Go to the EBE config, and disable `Enhanced Shulker Boxes`

### Expected behavior

The icons and labels should appear

### Log files

https://gist.github.com/RottenAppleSalt/55b4e6f0b20254bf516419ce65a84691

### Screenshots

Enabled EBE Shulkers (not working) - ![image](https://github.com/henkelmax/peek/assets/143226231/ac6ee729-7c53-4c7b-8921-8b312f8e9f75)
Disabled EBE Shulkers (working) ![image](https://github.com/henkelmax/peek/assets/143226231/d805ca1f-bd4c-4c15-92ff-5897989610a5)

**Comment by henkelmax** [comment]
Yeah this is completely normal. This mod completely changes the rendering of the blocks.
