### ISSUE TITLE
Feature Request: Preserve location of empty slots on shulker peek.

### ISSUE THREAD

**Issue by EvModder** [henkelmax/peek#37]
### Bug description

When peeking e.g., Enderchest, the order "blank spaces" is preserved between items. However, when hovering over a shulker, the tooltip preview moves all the empty slots to the end of the display. This can be solved somewhat ingame by filling empty slots with dummy items, but if it's possible to do from the mod's end that would be wonderful.

If it requires extra caching, or some setting to be enabled (which is off by default), that would still be completely fine for me, I'd just love to have the option

### Minecraft version

1.21

### Mod version

1.21

### Mod loader and version

Fabric loader 0.16.9

### Steps to reproduce

View peek tooltip for a shulker

### Log files

No log since this is a FR.. Sorry couldn't find the FR bug template.

**Comment by henkelmax** [comment]
![image](https://github.com/user-attachments/assets/3ace1bd8-2b8e-4877-8d78-5d07f460ed2e)

**Comment by EvModder** [comment]
Ahh my bad.
Tested on a vanilla server and yes it works the way it should. I assume the other server I was playing on modifies the packets, probably as part of their anticheat, which unfortunately removes the empty slots
